
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";


export const FETCH_ABONNEMENTS_REQUEST = 'FETCH_ABONNEMENTS_REQUEST';
export const FETCH_ABONNEMENTS_SUCCESS = 'FETCH_ABONNEMENTS_SUCCESS';
export const FETCH_ABONNEMENTS_FAILURE = 'FETCH_ABONNEMENTS_FAILURE';

export const CREATE_ABONNEMENT_REQUEST = 'CREATE_ABONNEMENT_REQUEST';
export const CREATE_ABONNEMENT_SUCCESS = 'CREATE_ABONNEMENT_SUCCESS';
export const CREATE_ABONNEMENT_FAILURE = 'CREATE_ABONNEMENT_FAILURE';

export const UPDATE_ABONNEMENT_REQUEST = 'UPDATE_ABONNEMENT_REQUEST';
export const UPDATE_ABONNEMENT_SUCCESS = 'UPDATE_ABONNEMENT_SUCCESS';
export const UPDATE_ABONNEMENT_FAILURE = 'UPDATE_ABONNEMENT_FAILURE';

export const DELETE_ABONNEMENT_REQUEST = 'DELETE_ABONNEMENT_REQUEST';
export const DELETE_ABONNEMENT_SUCCESS = 'DELETE_ABONNEMENT_SUCCESS';
export const DELETE_ABONNEMENT_FAILURE = 'DELETE_ABONNEMENT_FAILURE';
